/*
 *  음악이름(String)
	가수이름(String)
	장르(String)
	재생시간(String / 5:45)
	앨범판매수(inst)
	발매일(date)
 */


CREATE TABLE TB_MUSIC(
	MUSIC_NUM NUMBER  PRIMARY KEY,
	MUSIC_NAME VARCHAR2(50) NOT NULL,
	SINGER_NAME VARCHAR2(50) NOT NULL,
	GENRE_NAME VARCHAR2(20)NOT NULL,
	PLAY_TIME VARCHAR2(20)NOT NULL,
	ALBUM_SELL NUMBER NOT NULL,
	RELEASE_DATE DATE NOT NULL
)


DROP SEQUENCE SEQ_NUSIC_NUM;
CREATE SEQUENCE SEQ_MUSIC_NUM
NOCACHE;

INSERT
  INTO
       TB_MUSIC
VALUES(SEQ_MUSIC_NUM.NEXTVAL, '바람이 불어오는곳', '김광석', '포크', '3분 22초', 0, TO_DATE('1994-06-25', 'YYYY-MM-DD'));
INSERT INTO TB_MUSIC
VALUES(SEQ_MUSIC_NUM.NEXTVAL, 'Next Level', '에스파', 'K-POP', '3분 40초', '2000000', TO_DATE('2021-05-17', 'YYYY-MM-DD')); )

COMMIT;

DROP TABLE TB_MUSIC;

SELECT * FROM TB_MUSIC